/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: iirFilter.c
 *
 * MATLAB Coder version            : 5.3
 * C/C++ source code generated on  : 10-Jul-2022 17:29:38
 */

/* Include Files */
#include "iirFilter.h"
#include "iirFilter_data.h"
#include "iirFilter_initialize.h"
#include "iirFilter_types.h"

/* Function Definitions */
/*
 * DOFILTER 对输入 x 进行滤波并返回输出 y。
 *
 * Arguments    : double x
 * Return Type  : double
 */
double iirFilter(double x)
{
  dsp_BiquadFilter_0 *obj;
  double denAccum;
  double tmpState;
  double y;
  if (!isInitialized_iirFilter) {
    iirFilter_initialize();
  }
  /*  MATLAB Code */
  /*  Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13. */
  /*  Generated on: 10-Jul-2022 16:13:51 */
  /*  要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入
   * 'help codegen'。 */
  obj = &Hd.cSFunObject;
  /* System object Outputs function: dsp.BiquadFilter */
  denAccum = obj->P3_RTP3COEFF[0] * x;
  denAccum -= obj->P2_RTP2COEFF[0] * obj->W0_FILT_STATES[0];
  tmpState = denAccum - obj->P2_RTP2COEFF[1] * obj->W0_FILT_STATES[1];
  denAccum = obj->P1_RTP1COEFF[0] * tmpState;
  denAccum += obj->W0_FILT_STATES[0] * obj->P1_RTP1COEFF[1];
  denAccum += obj->W0_FILT_STATES[1] * obj->P1_RTP1COEFF[2];
  obj->W0_FILT_STATES[1] = obj->W0_FILT_STATES[0];
  obj->W0_FILT_STATES[0] = tmpState;
  denAccum *= obj->P3_RTP3COEFF[1];
  denAccum -= obj->P2_RTP2COEFF[2] * obj->W0_FILT_STATES[2];
  tmpState = denAccum - obj->P2_RTP2COEFF[3] * obj->W0_FILT_STATES[3];
  denAccum = obj->P1_RTP1COEFF[3] * tmpState;
  denAccum += obj->W0_FILT_STATES[2] * obj->P1_RTP1COEFF[4];
  y = denAccum + obj->W0_FILT_STATES[3] * obj->P1_RTP1COEFF[5];
  obj->W0_FILT_STATES[3] = obj->W0_FILT_STATES[2];
  obj->W0_FILT_STATES[2] = tmpState;
  return y;
}

/*
 * DOFILTER 对输入 x 进行滤波并返回输出 y。
 *
 * Arguments    : void
 * Return Type  : void
 */
void iirFilter_free(void)
{
  if (!Hd.matlabCodegenIsDeleted) {
    Hd.matlabCodegenIsDeleted = true;
  }
}

/*
 * DOFILTER 对输入 x 进行滤波并返回输出 y。
 *
 * Arguments    : void
 * Return Type  : void
 */
void iirFilter_init(void)
{
  Hd.matlabCodegenIsDeleted = true;
}

/*
 * File trailer for iirFilter.c
 *
 * [EOF]
 */
